// Barrel export — foundation + Gold Mouf Dog components.
export { Nav } from './Nav'
export { Footer } from './Footer'
export { SplitText } from './SplitText'
export { MagneticBtn } from './MagneticBtn'
export { ScrollReveal } from './ScrollReveal'
export { VideoScrub } from './VideoScrub'
export { HeroSlider } from './HeroSlider'

export { RootLayout } from './RootLayout'
export { SilverTicker } from './SilverTicker'
export { ChatWidget } from './ChatWidget'
export { ToothMap, centerSelection, countSelected } from './ToothMap'
export type { ToothMapProps, ArchName, ToothTone } from './ToothMap'
export { ProductMedia } from './ProductMedia'
export { ProductCard } from './ProductCard'
export { Marquee } from './Marquee'
export { JewlxEmbed } from './JewlxEmbed'
export { Container, Section, Eyebrow, Heading, Btn, Rule } from './ui'
